### ISSUE TITLE
No InstantWP.exe in latest beta

### ISSUE THREAD

**Issue by d4nc00per** [corvideon/InstantWP#17]
I'm unable to start the app using the latest beta download `IWP-5.0.0-rc4-Win.zip`

See the screenshot.
![instantwp](https://cloud.githubusercontent.com/assets/5233036/21956122/479354e2-da71-11e6-9505-9b6619ddd940.png)

**Comment by corvideon** [comment]
Thanks! I will take a look.

**Comment by corvideon** [comment]
Sorry d4nc00per, can you confirm one thing? I had issues like this when my path on Windows has some entries in there that were missing. It caused all sorts of weirdness locally (Windows could not find system32 for instance). The SO question below might help:

http://stackoverflow.com/questions/4405091/how-do-you-avoid-over-populating-the-path-environment-variable-in-windows

There could still be an issue in IWP, but at least we can rule out something local first.
I will still try to recreate / fix it locally.

Thanks!
Seamus

**Comment by d4nc00per** [comment]
Hi, thanks for coming back to me. Looks like it's only minimal on this machine:

![image](https://cloud.githubusercontent.com/assets/5233036/21966423/c4919f90-db6a-11e6-8f37-31ec6d6cc3e1.png)

I tried building the source and got a bunch of errors, that resulted in a build similar to what I downloaded, so I figured it was a problem with that. Let me know if there's anything else I can do to help. :)

**Comment by corvideon** [comment]
Hi

Can you try changing the file Start-InstantWP.bat to below?
It appears the path to the bin folder is not being set properly.

@echo off
setlocal
cd /d %~dp0

echo IWP Startup
title IWP Startup
set IWPROOT=%~dp0
iwpcli start
iwpcli hide_vm
cd %IWPROOT%\bin\
start InstantWP.exe %IWPROOT%
%IWPROOT%\platform\win\nircmd\nircmdc.exe win hide title "IWP Startup"
exit /b

**Comment by d4nc00per** [comment]
This still gives the same error. I can't find any InstantWP.exe that it's referring to on line 11. My bin folder only contains an images folder. Is there an rc5 now?

**Comment by d4nc00per** [comment]
This is fixed in rc5. Thanks for the help and keep up the good work!

**Comment by corvideon** [comment]
Great news! Can I ask what the performance is like?
How much RAM is in your machine?
I have had reports that the last build was too slow.
