### ISSUE TITLE
Location of iwpserver and issue with iwpcli.exe

### ISSUE THREAD

**Issue by viktorix** [corvideon/InstantWP#21]
I installed InstantWP, and ran into an issue with a plugin upgrade:

> Update Failed: The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions.

So I wanted to find server files and included console to see if I can update permissions. But I can't figure out where iwp installs server files. Would appreciate if you could point me in the right direction.

Also, when I try to open iwpcli.exe it closes. So I can't open console.

This is what I got:
![image](https://cloud.githubusercontent.com/assets/1692600/22143024/8c567fec-dec6-11e6-938e-acb237155958.png)

I'm using v5 rc5. I think that's the latest one. I'm on Win 10.

**Comment by corvideon** [comment]
That fix is in Github and will be in the next release (a few days time).
If you want to test it locally, just change the file below:

https://github.com/corvideon/InstantWP/blob/master/core/platform/win/sync/scp.script

The server files are located inside the VM not in the Windows file system :)
You can login via ssh at the command line using the command below:

iwpcli ssh

You could also use the supplied WinSCP in the platform/win/sync folder. The login details below should work:

server: 127.0.0.1
port: 10080
user: root
password: root
