### ISSUE TITLE
The links in the docs are broken.

### ISSUE THREAD

**Issue by wormeyman** [corvideon/InstantWP#36]
For example https://github.com/corvideon/InstantWP/blob/master/core/docs/about.html#L345 is currently:

```html
<a href="">https://github.com/corvideon/InstantWP </a> </p>
```

but it should be 

```html
<a href="https://github.com/corvideon/InstantWP">https://github.com/corvideon/InstantWP</a> </p>
```

If you would like I could create a pull request fixing the links, are you using the Markdown to create the HTML versions? If so I could fixup the mark down files and then you could re-generate the html.

**Comment by corvideon** [comment]
Fixed in v5.1.0 -rc6 :)
