### ISSUE TITLE
Quick Heal blocked PUA.HideExec.A6

### ISSUE THREAD

**Issue by KoolPal** [corvideon/InstantWP#41]
Hi,
I  am not sure of this is a false alarm but QuickHeal on my machine blocked PUA.HideExec.A6 in the latest release.

Please guide.

**Comment by corvideon** [comment]
This is a known issue and a false alarm. I will be removing the open source component that caused this in the next build.

**Comment by corvideon** [comment]
Removed nircmd and replace with custom Racket based component.
