### ISSUE TITLE
Multiple IWP-5 Instances not working?

### ISSUE THREAD

**Issue by corvideon** [corvideon/InstantWP#49]
Summary - I tried to get two IWP instances running at the same time using 10000port and 11000port versions. The 11000port version will not work either as a second IWP or as a stand-alone.

I created two folders containing IWP-5 and change the second folders config file to use port 11000.
I started the first IWP instance using port 10000 and it started okay.
I started the second IWP instance using port 11000 and got a failed to load error.

I quit both IWP instances and then neither IWP versions would work - see below:

Started the second, port 11000 version by itself and got a failed to load error.
I quit the port 11000 version and started the port 10000 version and got a failed to load error.
So, I restarted my computer and started the 10000port version. It started okay.
I quit the 10000port version and started the 11000port version and got a failed to load error.
I quit the 11000port version and started the 10000port version and it worked Okay.

**Comment by thomasbonsirven** [comment]
hello,
what your version to Windows or mac please. vzacause in Windows7 i have not error.

but i have this error if dont quit easyphp or other webserver local. (usbwebserver etc... )

Thomas B

**Comment by corvideon** [comment]
Hi Thomas

I have tested IWP v5 on Windows 7 and Windows 10.

Regards

Seamus

**Comment by corvideon** [comment]
This is now fixed as outlined in the FAQ and the wiki.

**Comment by thomasbonsirven** [comment]
Hello,

Well, Thanks, i test this...

Great Job.
