### ISSUE TITLE
Checking if WordPress can make requests to itself from 127.0.0.1

### ISSUE THREAD

**Issue by elEglon** [corvideon/InstantWP#59]
Trying to use the Simply Static Plugin there is a little Problem:
As InstantWP not seems to be able to make requests to itself, using Simply Static fails.

If it's an easy fix for you, I would like to see this done.

Thank you in advance an best wishes
Eglon

**Comment by corvideon** [comment]
Thanks for that! I will look into this as this is something I would like to use myself.

**Comment by corvideon** [comment]
This issue has also be reported when using the wp cron test. You get an error 'Error: WP-Cron spawn failed with error: cURL error 7: Failed to connect to 127.0.0.1 port 10080: Connection refused'.

**Comment by corvideon** [comment]
Another issue - When editing main theme (php) files using the build in WordPress editor after upgrading to version 4.9. I get the following error:

"Unable to communicate back with site to check for fatal errors, so the PHP change was reverted. You will need to upload your PHP file change by some other means, such as by using SFTP."

**Comment by ybf2u** [comment]
I am interested in using Simply Static with IWP, too, and would like to see this problem solved.

**Comment by seamus-brady** [comment]
This bug goes a bit deeper than I suspected and has to do with issues in port forwarding from the Linux VM to the host OS. I doubt I will be able to create a trivial fix, so I am giving a workaround for now that will do the static site thing for those who need it...

Wget can do this.

Create a folder for the static copy of the site. Then open a command prompt there and type the following all on one line and hit enter:

`wget --mirror --convert-links --backup-converted --adjust-extension http://127.0.0.1:10080/wordpress/`

This will create a static copy of the InstantWP website for you.

Get wget for windows: https://eternallybored.org/misc/wget/

Get wget on macOS using HomeBrew: https://stackoverflow.com/questions/4572153/os-x-equivalent-of-linuxs-wget#4572158

**Comment by ybf2u** [comment]
Hi Seamus,

I hope you are doing well during this pandemic!

Several years ago we discussed a bug in InstantWP (see below) which you temporarily solved with wget.  I am writing to see if there has been any progress on this issue since then.

All the best,
Yitna

Yitna Firdyiwek, PhD
Instructional Designer
Arts & Science Learning Design & Technology
University of Virginia
ybf2u@virginia.edu

**Comment by seamus-brady** [comment]
Sorry Yitna, IWP now has a new owner :)

**Comment by ybf2u** [comment]
Oh, sorry to have bothered you.  Congratulations, by the way!  I hope you are off to bigger and better projects. 😊

.y
