### ISSUE TITLE
problem after upgrading IWP from 4.5 to 5 : SimpleXML extension must be enabled in php.ini.

### ISSUE THREAD

**Issue by jpgoem** [corvideon/InstantWP#61]
After upgrading to InstantWP V5 (from 4.5), the plugin Smart Slider 3 (by Nextend) immediately gives the following message : "SimpleXML extension must be enabled in php.ini. Please contact your server administrator to enable it for you." 
The plugin is no longer working.
Is this related to php 7 ?
Any idea how to enable SimpleXML ? I don't find it in php.ini.

**Comment by corvideon** [comment]
Hi JPGoem

Try opening up an SSH Terminal and typing:

sudo apk update
sudo apk add php7-simplexml

Hope that helps

**Comment by jpgoem** [comment]
Thanks a lot for the solution : it works !
