### ISSUE TITLE
wordpress performance issue

### ISSUE THREAD

**Issue by JBX028** [corvideon/InstantWP#66]
Hi,

Not sure why but wordpress admin is very very slow. Some pages aren't accessible at all. I have installed 8 plugins (including WooCommerce) and when I deactivate them, the performances are better (all pages are accessible) but the system remains slow.
I have tried all things visible in google (5 top result with "wordpress admin performance slow") such as installing an use extensions like wp-optimize, transients manager, P3 optimizer, but without success and the ouput of P3 is just amazing(!):

![image](https://user-images.githubusercontent.com/88729/34176600-c72793e0-e500-11e7-84f0-d28e1ec96629.png)

I have tried to increase the memory up to 1024 but I don't see any real differences. My PC is a recent one and all software's work just fine.
I don't know what to do. Does anyone have any ideas?

Regards

**Comment by corvideon** [comment]
Hmm. Well IWP will always be a bit slower when compared to a native tool like MAMP but not that much slower :) If the site is huge (a large database) that might also be the cause? Can you try adding more RAM and see if that helps? 2056 perhaps?

**Comment by JBX028** [comment]
Hi,

Thanks for your reply. Since, I've made additional investigations by reinstalling everything from scratch and gradually install plugins one by one and I realized that some menu are not accessible after the installation of woocommerce but not immediatly after the install but after sometime.

Overall this is a bit slow but still usable but 3 menus (the one to change the header, the background and personnalize as well) doesn't work anymore at all which is a pain because I cannot change the layout of the site. 

I have try to set 2056 already but I think the limit is 1024 because the server doesn't start with such amount of memory.

I am surprise to be the first one with this issue and this is not related to my PC configuration because I tried with another recent PC with 16GB of RAM and the issue is the same.

I will probably switch to MAMP but I really liked the approach and flexibility of InstandWP with 1 folder per site and nothing to install.

**Comment by corvideon** [comment]
Sorry JBX, that should have been 2048MB :) My mistake - typing on the go.
I have some customers using woocommerce and it works OK.  You may have just hit on a particular combination of theme, plugin and other things that causes a spike in RAM/CPU usage? If you tell me the specifics I will take a look myself. Maybe there is something in the setup that can be tweaked. Sorry about that :(

**Comment by JBX028** [comment]
Hi,

Well I have indeed set 2048 but QEMU crashes with that number.
Not sure if you can download the folder and try to run it on your machine?

https://drive.google.com/file/d/19ZQjcUnC90yQiTwmrpzhQ7MCaC6ohLwf/view?usp=sharing

Thanks in advance. No worry if you cannot I fully understand

Regards,






2018-01-03 20:34 GMT+01:00 Seamus Brady <notifications@github.com>:

**Comment by corvideon** [comment]
Hi JBX

I took a quick look at the site on my Mac (just copied the qcow2 file from the VM folder over) and ran it with 2000MB of RAM. It runs OK but is is slow. I looked at the database and the uploads and I think one of the culprits is the 2500+ files in the /var/www/localhost/htdocs/wordpress/wp-content/uploads/2017/12 - Apache may be choking on these a bit at the beginning perhaps? Can you try a smaller amount here and see if that helps? The rest of the site looks OK but it was only a quick look after all. :)

Hope that helps

Regards

Seamus

**Comment by JBX028** [comment]
Hi,
I have deleted almost all the pictures in /var/www/localhost/htdocs/
wordpress/wp-content/uploads/2017/12 but with no effects. Last question,
are you really able to start the vM with 2048 of RAM?
When I set this value, I don't see anything special when the tool starts
but I cannot access wordpress and when I close instantWP afterward, an
error message is visible and however the amount of free RAM available on my
computer is higher than 2GB.....

Regards,

2018-01-04 23:53 GMT+01:00 Seamus Brady <notifications@github.com>:

**Comment by JBX028** [comment]
Hi,
1800MB works fine but still the system is too slow or even not accessible for some pages that I am going to use another solution.
Anyway, thanks for your help this week
