### ISSUE TITLE
Add support for SMP switch to IWP

### ISSUE THREAD

**Issue by corvideon** [corvideon/InstantWP#67]
See 

-smp [cpus=]n[,cores=cores][,threads=threads][,sockets=sockets][,maxcpus=maxcpus]

http://qemu.weilnetz.de/doc/qemu-doc.html

"Simulate an SMP system with n CPUs. On the PC target, up to 255 CPUs are supported. On Sparc32 target, Linux limits the number of usable CPUs to 4. For the PC target, the number of cores per socket, the number of threads per cores and the total number of sockets can be specified. Missing values will be computed. If any on the three values is given, the total number of CPUs n can be omitted. maxcpus specifies the maximum number of hotpluggable CPUs"

**Comment by seamus-brady** [comment]
Not supported in x86 version of QEMU.
