### ISSUE TITLE
InstantWP is very slow

### ISSUE THREAD

**Issue by Joxweb** [corvideon/InstantWP#70]
Hello,

I have installed the new InstantWP release but it's very slow to start and after in WordPress, each step is very slow too.

My configuration : windows 8.1 64bits + 8Go RAM + Intel core i7-4500U @ 1.80 GHz 2.40 GHz
D disk with 400 Go free space
InstantWP5.3.5
Theme : Flatsome (with WooCommerce)
Size : less than 1Go

I have increase the amount of RAM to 1024 in InstantWP but I have no change (I tried 2048 but it crashes InstantWP)

Is that normal ? Do you have some tips to improve performance ?

Thanks in advance for your help.

PS 1 : I worked before with the 4.5 release and it was super until I need to change because of WordPress Plugins compatibility with PHP release.
PS 2 : I'm not techie
PS 3 : sorry for my poor english :-)

**Comment by seamus-brady** [comment]
Try putting the RAM up to 1900 and see if that helps.
This version uses different technology so on some systems it may be slower, but it should still be usable.

The troubleshooting guide lists some ways to improve speed:

https://github.com/corvideon/InstantWP/wiki/Troubleshooting-InstantWP-start-up-issues
