### ISSUE TITLE
Trouble Running Multiple Installations of InstantWP

### ISSUE THREAD

**Issue by businessomatic** [corvideon/InstantWP#71]
I found that I cannot click the Web Console button. I cannot change the tables.

**Comment by seamus-brady** [comment]
Please follow the instructions below:

https://github.com/corvideon/InstantWP/wiki/Running-multiple-installations-of-InstantWP-at-the-same-time

Once you have updated the system, use the troubleshooter below if the installation does not start:

https://github.com/corvideon/InstantWP/wiki/Troubleshooting-InstantWP-start-up-issues
