### ISSUE TITLE
Cannot re login

### ISSUE THREAD

**Issue by Draven0914** [corvideon/InstantWP#72]
I am having an issue with InstantWP where after i log out and try to go back to InstantWP later on and click on WordPressadmin NOTHING happens......it just sits there can someone please hel me figure this out

Thank You

**Comment by seamus-brady** [comment]
Please try the troubleshooting guide - especially the sections on restarting the server:

https://github.com/corvideon/InstantWP/wiki/Troubleshooting-InstantWP-start-up-issues
