### ISSUE TITLE
instantwp does not open

### ISSUE THREAD

**Issue by kocak76** [corvideon/InstantWP#73]
hi there
i have just installed the latest version of the instantwp and downloaded to my pc laptop. The main menu appeared and I clicked Wordpress Admin but it does not open the dashboard. I have waited long time.
I have also disabled the firewall but it still does not open the dashboard.

Please help.

**Comment by seamus-brady** [comment]
Please try the troubleshooting guide - especially the sections on restarting the server:

https://github.com/corvideon/InstantWP/wiki/Troubleshooting-InstantWP-start-up-issues
