### ISSUE TITLE
Can't open InstantWP 

### ISSUE THREAD

**Issue by Jessica8609** [corvideon/InstantWP#74]
Hi, 

I can no longer open InstantWP and I have tried all of the steps/suggestions at the FAQ, support, online forums, everything. Nothing works. I am getting the attached error message when I try to open InstantWP - none of the control/advanced control panel buttons work either. I have tried moving to a different location/file path, that didn't work either. Any suggestions? Thank you. 

![screen shot 2018-04-04 at 20 52 54](https://user-images.githubusercontent.com/38085364/38332504-0d6466b2-384e-11e8-9c88-4e83449919bd.png)

**Comment by seamus-brady** [comment]
Please try the troubleshooting guide - especially the sections on restarting the server:

https://github.com/corvideon/InstantWP/wiki/Troubleshooting-InstantWP-start-up-issues
