### ISSUE TITLE
Unable to start SSH Terminal (windows 10)

### ISSUE THREAD

**Issue by instantwpuserwin** [corvideon/InstantWP#75]
Hi:

I installed successfully.
Control panel comes up.

However, I cannot launch frontpage or admin.  Nothing happens when I click on these buttons.
So launched "Php Info" and http://127.0.0.1:10080/phpinfo.php is launched with a "This site can’t be reached"error.
So I think web server is not lauched.

I also tried lauching SSH terminal. But DOS windows comes up, display something and shuts down.
I cannot see what the error message is:

Please help resolve.

Notse: 
1>So I already tried changing  RAM to 1024 in config, restarted server.    But issue still there.
2> I also have AVG and Microsoft defender installed, But disabled it temporarily.

Thanks

**Comment by webtoolsgroup** [comment]
Please take a look at the troubleshooter below:

https://github.com/webtoolsgroup/InstantWP/wiki/Troubleshooting-InstantWP-start-up-issues

This should help you figure out what the issue is.
