### ISSUE TITLE
Urgent! php update in InstantWP4.5

### ISSUE THREAD

**Issue by evercwb** [corvideon/InstantWP#76]
Hello, I need help using version 4.5 of InstantWP, I do not want to migrate to version 5 even because of the incompatibility of the operating system. I need only update the version of PHP to a newer one since the one in InstantWP 4.5 uses php 5. Can anyone help me with the apache configuration? 

Thank you.

**Comment by webtoolsgroup** [comment]
Sorry evercwb - there is no way to upgrade the version of PHP in v4.5.
It is hardcoded and compiled in.
