### ISSUE TITLE
HELP GOING NUTZ

### ISSUE THREAD

**Issue by kvz1r** [corvideon/InstantWP#92]
I have recently last few months experimented  with IWP IWP-v5.3.x, I have installed it multiple times on 3 different Win 10 machines 2 pro 1 home. After a lot of troubleshooting following all available documentation still would not execute fully installed to NAS DRIVE AND WALA NO IDENTIFIABLE  REASON STARTED WORKING USED FOR 3 DAYS . Shut down  now all  8  different installs and locations refuse to connect with the following a connection to the server at 127.0.0.1:10080 or similar response from Chrome/Firefox/BRAVE Not a genius but almost 30 years as advanced user setting up LANS etc Can anyone point me to why I cannot get  IWP or anything else to connect to to the server at 127.0.0.1 AKA Local Host ? Thanx in advance to all who respond :) Looks like my issue is rooted in http://127.0.0.1:10080 and IE  one of the 6 browsers notified me  

The remote device or resource won't accept the connection | The remote device or resource won't accept the connection
-- | --
The device or resource (127.0.0.1) is not set up to accept connections on port  "10080".

now i am really lost and have lost 40-60 hours work 
--

**Comment by celtic-coder** [comment]
Unfortunately, as noted in #90, there will probably be no help from @webtoolsgroup.

**Comment by VincentProuchet** [comment]
well this look like a firewall configuration issue
but it can also be due to a folder filename change
make sur it doesn't have any space in it "yhea_because_it_sometimes_shit_in_the_fan"

**Comment by kvz1r** [comment]
Thanks , Shame used to use the old version of Instant-WP some 8 years 
ago good stuff and not beyond the average tech to resolve issues - this 
newer version quite a bit more complex to unravel issues Thanks for your 
response
:'-(
------ Original Message ------

**Comment by VincentProuchet** [comment]
did you solved your issue ?
if yes what was it ?

**Comment by kvz1r** [comment]
**Psycho99 - NO I HAVEN'T :( :( :(** Really Upset as I know there are other development platforms such as Local by Flywheel etc  , but as way back user of InstantWP I think it is/was by far the best. I am going to leave this posted in hopes another user may have experienced A similar they overcame an can advise on a solution. I have 4 WIN 10 PC's can not get it to run on any at this point. It is definitely something to do with  Windows local host/http:/127.0.0.1:10080  and it being correctly configured to communicate with the Linux Virtual Server I am falling back to LOCAL until I get some helpful feed back - this level of technical expertise is way above my pay grade , although I don't have a pay grade:( lol hopefully someone will chime in if they are browsing these issues by chance and offer some assistance. If and when I do get a solution I will post hoe it was resolved in detail so that others may be able to learn from it and keep all their hair , almost 60 y/o and have a lot less after a week stressing night and day over InstantWP

**Comment by kvz1r** [comment]
Psycho99 - NO I HAVEN'T :( :( :( Really Upset as I know there are other development platforms such as Local by Flywheel etc  , but as way back user of InstantWP I think it is/was by far the best. I am going to leave this posted in hopes another user may have experienced A similar they overcame an can advise on a solution. I have 4 WIN 10 PC's can not get it to run on any at this point. It is definitely something to do with  Windows local host/http:/127.0.0.1:10080  and it being correctly configured to communicate with the Linux Virtual Server I am falling back to LOCAL until I get some helpful feed back - this level of technical expertise is way above my pay grade , although I don't have a pay grade:( lol hopefully someone will chime in if they are browsing these issues by chance and offer some assistance. If and when I do get a solution I will post hoe it was resolved in detail so that others may be able to learn from it and keep all their hair , almost 60 y/o and have a lot less after a week stressing night and day over InstantWP
